# 1. ?????? ???? (??????? ???? ?? ?????? ?????)
spring.datasource.url=jdbc:postgresql://localhost:5432/fsociety_db
# 2. ???? ????? ?? ???? (???????? postgres)
spring.datasource.username=postgres
# 3. ???? ?????? (???, ?? ?? ?????? ??? ????????? PostgreSQL)
spring.datasource.password=QuxwelAdmin

# 4. ??????? (?????????? ??? Java ?? SQL)
spring.datasource.driver-class-name=org.postgresql.Driver

# 5. ?????: ?????? ??? ???????? ??????? ?? ?????? Entity (update ??????? "???????????")
spring.jpa.hibernate.ddl-auto=update

# 6. ?????????? ? ??????? SQL-?????? (??? ?? ?????, ?? ??????? ?????? ???)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
app.payment.secret=QuxwelAdvice
